backend:
  name: git-gateway
  branch: main
media_folder: "../images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "../index.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Text", name: "hero_text", widget: "string"}
      - label: "About"
        name: "about"
        file: "../about.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}
      - label: "Contact"
        name: "contact"
        file: "../contact.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}
  - name: "projects"
    label: "Projects"
    folder: "../projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["residential", "commercial", "eco"]}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}